// flow-typed signature: af79b80e002a100c10df15fae9115f0c
// flow-typed version: <<STUB>>/@commitlint/prompt_v^6.1.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@commitlint/prompt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@commitlint/prompt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@commitlint/prompt/lib/index' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/input' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/enum-rule-is-active' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/format' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/get-forced-case-fn' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/get-forced-leading-fn' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/get-has-name' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/get-prompt' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/get-prompt.test' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/get-rule-name' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/meta' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/rule-is-active' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/library/rule-is-applicable' {
  declare module.exports: any;
}

declare module '@commitlint/prompt/lib/settings' {
  declare module.exports: any;
}

// Filename aliases
declare module '@commitlint/prompt/lib/index.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/index'>;
}
declare module '@commitlint/prompt/lib/input.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/input'>;
}
declare module '@commitlint/prompt/lib/library/enum-rule-is-active.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/enum-rule-is-active'>;
}
declare module '@commitlint/prompt/lib/library/format.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/format'>;
}
declare module '@commitlint/prompt/lib/library/get-forced-case-fn.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/get-forced-case-fn'>;
}
declare module '@commitlint/prompt/lib/library/get-forced-leading-fn.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/get-forced-leading-fn'>;
}
declare module '@commitlint/prompt/lib/library/get-has-name.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/get-has-name'>;
}
declare module '@commitlint/prompt/lib/library/get-prompt.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/get-prompt'>;
}
declare module '@commitlint/prompt/lib/library/get-prompt.test.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/get-prompt.test'>;
}
declare module '@commitlint/prompt/lib/library/get-rule-name.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/get-rule-name'>;
}
declare module '@commitlint/prompt/lib/library/meta.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/meta'>;
}
declare module '@commitlint/prompt/lib/library/rule-is-active.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/rule-is-active'>;
}
declare module '@commitlint/prompt/lib/library/rule-is-applicable.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/library/rule-is-applicable'>;
}
declare module '@commitlint/prompt/lib/settings.js' {
  declare module.exports: $Exports<'@commitlint/prompt/lib/settings'>;
}
