// flow-typed signature: 8be8ed6e238d3e47b3c6bf3066a6abe7
// flow-typed version: <<STUB>>/babel-inline-import-loader_v^0.0.5/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-inline-import-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-inline-import-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-inline-import-loader/example/index' {
  declare module.exports: any;
}

declare module 'babel-inline-import-loader/example/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-inline-import-loader/example/index.js' {
  declare module.exports: $Exports<'babel-inline-import-loader/example/index'>;
}
declare module 'babel-inline-import-loader/example/webpack.config.js' {
  declare module.exports: $Exports<'babel-inline-import-loader/example/webpack.config'>;
}
declare module 'babel-inline-import-loader/index' {
  declare module.exports: $Exports<'babel-inline-import-loader'>;
}
declare module 'babel-inline-import-loader/index.js' {
  declare module.exports: $Exports<'babel-inline-import-loader'>;
}
