// flow-typed signature: 0ba90aa93a6e36066eedaacc1f32bc21
// flow-typed version: <<STUB>>/babel-plugin-inline-dotenv_vhttps://github.com/blackxored/babel-plugin-inline-dotenv#fix/relative-paths/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-inline-dotenv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-inline-dotenv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-inline-dotenv/index' {
  declare module.exports: $Exports<'babel-plugin-inline-dotenv'>;
}
declare module 'babel-plugin-inline-dotenv/index.js' {
  declare module.exports: $Exports<'babel-plugin-inline-dotenv'>;
}
