// flow-typed signature: afd0d66f449ac03f162e6c5fa3e65131
// flow-typed version: <<STUB>>/change-case_v^3.0.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'change-case'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'change-case' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'change-case/change-case' {
  declare module.exports: any;
}

// Filename aliases
declare module 'change-case/change-case.js' {
  declare module.exports: $Exports<'change-case/change-case'>;
}
