// flow-typed signature: 247becef9a3dee9298aa36ea85df0a9d
// flow-typed version: <<STUB>>/glamorous-primitives_v^2.1.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'glamorous-primitives'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'glamorous-primitives' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'glamorous-primitives/lib/constants' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/constructor/create-glamorous' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/constructor/prepare-styles' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/constructor/split-props' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/figures/theme-provider' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/figures/with-theme' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/index' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/injector/platform' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/utils/aliases' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/utils/get-styles' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/utils/is-primitive-prop' {
  declare module.exports: any;
}

declare module 'glamorous-primitives/lib/utils/should-forward-property' {
  declare module.exports: any;
}

// Filename aliases
declare module 'glamorous-primitives/lib/constants.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/constants'>;
}
declare module 'glamorous-primitives/lib/constructor/create-glamorous.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/constructor/create-glamorous'>;
}
declare module 'glamorous-primitives/lib/constructor/prepare-styles.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/constructor/prepare-styles'>;
}
declare module 'glamorous-primitives/lib/constructor/split-props.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/constructor/split-props'>;
}
declare module 'glamorous-primitives/lib/figures/theme-provider.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/figures/theme-provider'>;
}
declare module 'glamorous-primitives/lib/figures/with-theme.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/figures/with-theme'>;
}
declare module 'glamorous-primitives/lib/index.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/index'>;
}
declare module 'glamorous-primitives/lib/injector/platform.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/injector/platform'>;
}
declare module 'glamorous-primitives/lib/utils/aliases.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/utils/aliases'>;
}
declare module 'glamorous-primitives/lib/utils/get-styles.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/utils/get-styles'>;
}
declare module 'glamorous-primitives/lib/utils/is-primitive-prop.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/utils/is-primitive-prop'>;
}
declare module 'glamorous-primitives/lib/utils/should-forward-property.js' {
  declare module.exports: $Exports<'glamorous-primitives/lib/utils/should-forward-property'>;
}
