// flow-typed signature: 03ba45bee9f585643eb547554b84a8d0
// flow-typed version: <<STUB>>/prop-styles_v^2.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prop-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prop-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prop-styles/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prop-styles/lib/index.js' {
  declare module.exports: $Exports<'prop-styles/lib/index'>;
}
