// flow-typed signature: fd181402b2d6f7975eb3e72d099470f3
// flow-typed version: <<STUB>>/@storybook/addon-storysource_v^3.4.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-storysource'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-storysource' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-storysource/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/loader/default-options' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/loader/generate-helpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/loader/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/loader/inject-decorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/loader/parse-helpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/dist/StoryPanel' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/loader' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/src/loader/default-options' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/src/loader/generate-helpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/src/loader/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/src/loader/inject-decorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/src/loader/inject-decorator.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/src/loader/parse-helpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/src/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/src/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-storysource/src/StoryPanel' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-storysource/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/index'>;
}
declare module '@storybook/addon-storysource/dist/loader/default-options.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/loader/default-options'>;
}
declare module '@storybook/addon-storysource/dist/loader/generate-helpers.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/loader/generate-helpers'>;
}
declare module '@storybook/addon-storysource/dist/loader/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/loader/index'>;
}
declare module '@storybook/addon-storysource/dist/loader/inject-decorator.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/loader/inject-decorator'>;
}
declare module '@storybook/addon-storysource/dist/loader/parse-helpers.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/loader/parse-helpers'>;
}
declare module '@storybook/addon-storysource/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/manager'>;
}
declare module '@storybook/addon-storysource/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/preview'>;
}
declare module '@storybook/addon-storysource/dist/StoryPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/dist/StoryPanel'>;
}
declare module '@storybook/addon-storysource/loader.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/loader'>;
}
declare module '@storybook/addon-storysource/register.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/register'>;
}
declare module '@storybook/addon-storysource/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/src/index'>;
}
declare module '@storybook/addon-storysource/src/loader/default-options.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/src/loader/default-options'>;
}
declare module '@storybook/addon-storysource/src/loader/generate-helpers.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/src/loader/generate-helpers'>;
}
declare module '@storybook/addon-storysource/src/loader/index.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/src/loader/index'>;
}
declare module '@storybook/addon-storysource/src/loader/inject-decorator.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/src/loader/inject-decorator'>;
}
declare module '@storybook/addon-storysource/src/loader/inject-decorator.test.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/src/loader/inject-decorator.test'>;
}
declare module '@storybook/addon-storysource/src/loader/parse-helpers.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/src/loader/parse-helpers'>;
}
declare module '@storybook/addon-storysource/src/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/src/manager'>;
}
declare module '@storybook/addon-storysource/src/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/src/preview'>;
}
declare module '@storybook/addon-storysource/src/StoryPanel.js' {
  declare module.exports: $Exports<'@storybook/addon-storysource/src/StoryPanel'>;
}
